import {useEffect,useState} from "react";
import {SafeAreaView,ScrollView,StyleSheet,Text,TextInput,TouchableOpacity,View,ActivityIndicator} from "react-native";
import axios from "axios";
import * as SecureStore from "expo-secure-store";
const API_URL=process.env.EXPO_PUBLIC_API_URL||"http://10.0.2.2:5000/api/v1";
const api=axios.create({baseURL:API_URL});
type User={id:string;name:string;email:string;role:"ADMIN"|"STAFF"};
type Customer={_id:string;customerId:string;name:string;mobile:string;city?:string};
type Loan={_id:string;loanId:string;customerId:Customer;loanType:string;requiredAmount:number;status:string};
type Car={_id:string;vehicleId:string;registrationNumber:string;make:string;model:string;purchasePrice:number;status:string};
type Dashboard={customers:number;activeLoans:number;carsInInventory:number;carsSold:number;totalProfit:number};
export default function App(){const[user,setUser]=useState<User|null>(null);const[checking,setChecking]=useState(true);useEffect(()=>{SecureStore.getItemAsync("sm_token").then(async token=>{if(!token)return;try{const r=await api.get("/auth/me",{headers:{Authorization:"Bearer "+token}});setUser(r.data.data)}catch{await SecureStore.deleteItemAsync("sm_token")}}).finally(()=>setChecking(false))},[]);if(checking)return <SafeAreaView style={sStyle.safe}><View style={sStyle.center}><ActivityIndicator/><Text style={sStyle.muted}>Loading...</Text></View></SafeAreaView>;if(!user)return <Login onLogin={setUser}/>;return <Home user={user} onLogout={async()=>{await SecureStore.deleteItemAsync("sm_token");setUser(null)}}/>}
function Login({onLogin}:{onLogin:(u:User)=>void}){const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[error,setError]=useState("");const[busy,setBusy]=useState(false);async function submit(){setError("");setBusy(true);try{const r=await api.post("/auth/login",{email,password});await SecureStore.setItemAsync("sm_token",r.data.data.token);onLogin(r.data.data.user)}catch(e:any){setError(e?.response?.data?.message||"Unable to sign in.")}finally{setBusy(false)}}return <SafeAreaView style={sStyle.login}><View style={sStyle.loginCard}><Text style={sStyle.brand}>SM ASSOCIATE</Text><Text style={sStyle.loginTitle}>Management System</Text><Text style={sStyle.muted}>Secure mobile access</Text><Text style={sStyle.inputLabel}>Email</Text><TextInput autoCapitalize="none" keyboardType="email-address" value={email} onChangeText={setEmail} placeholder="admin@example.com" style={sStyle.input}/><Text style={sStyle.inputLabel}>Password</Text><TextInput secureTextEntry value={password} onChangeText={setPassword} placeholder="Password" style={sStyle.input}/>{error?<Text style={sStyle.error}>{error}</Text>:null}<TouchableOpacity style={sStyle.button} onPress={submit} disabled={busy}><Text style={sStyle.buttonText}>{busy?"Signing in...":"Sign in"}</Text></TouchableOpacity></View></SafeAreaView>}
function Home({user,onLogout}:{user:User;onLogout:()=>void}){const[tab,setTab]=useState("Dashboard");return <SafeAreaView style={sStyle.safe}><View style={sStyle.header}><View><Text style={sStyle.brand}>SM ASSOCIATE</Text><Text style={sStyle.headerTitle}>{tab}</Text></View><TouchableOpacity onPress={onLogout}><Text style={sStyle.signout}>Sign out</Text></TouchableOpacity></View><View style={sStyle.tabs}>{["Dashboard","Customers","Loans","Cars","Profit"].map(x=><TouchableOpacity key={x} style={tab===x?s.tabActive:s.tab} onPress={()=>setTab(x)}><Text style={tab===x?s.tabTextActive:s.tabText}>{x}</Text></TouchableOpacity>)}</View>{tab==="Dashboard"?<Dashboard/>:tab==="Customers"?<Customers/>:tab==="Loans"?<Loans/>:tab==="Cars"?<Cars/>:<Profit/>}</SafeAreaView>}
async function token(){return SecureStore.getItemAsync("sm_token")}
function Dashboard(){const[data,setData]=useState<Dashboard|null>(null);useEffect(()=>{token().then(t=>api.get("/reports/dashboard",{headers:{Authorization:"Bearer "+t}}).then(r=>setData(r.data.data)))},[]);return <ScrollView contentContainerStyle={s.container}><View style={sStyle.grid}><Stat title="Customers" value={data?.customers??0}/><Stat title="Active Loans" value={data?.activeLoans??0}/><Stat title="Cars in Stock" value={data?.carsInInventory??0}/><Stat title="Cars Sold" value={data?.carsSold??0}/></View><View style={sStyle.profitBox}><Text style={sStyle.label}>NET CAR PROFIT</Text><Text style={sStyle.profit}>₹{(data?.totalProfit??0).toLocaleString("en-IN")}</Text></View></ScrollView>}
function Customers(){const[data,setData]=useState<Customer[]>([]);const[name,setName]=useState("");const[mobile,setMobile]=useState("");const[message,setMessage]=useState("");const load=()=>token().then(t=>api.get("/customers",{headers:{Authorization:"Bearer "+t}}).then(r=>setData(r.data.data)));useEffect(()=>{load()},[]);async function add(){try{const t=await token();await api.post("/customers",{name,mobile},{headers:{Authorization:"Bearer "+t}});setName("");setMobile("");setMessage("Customer added.");load()}catch(e:any){setMessage(e?.response?.data?.message||"Unable to save.")}}return <ScrollView contentContainerStyle={s.container}><View style={sStyle.card}><Text style={sStyle.section}>Add Customer</Text><TextInput style={sStyle.input} placeholder="Customer name" value={name} onChangeText={setName}/><TextInput style={sStyle.input} placeholder="Mobile number" keyboardType="phone-pad" value={mobile} onChangeText={setMobile}/><TouchableOpacity style={sStyle.button} onPress={add}><Text style={sStyle.buttonText}>Save Customer</Text></TouchableOpacity>{message?<Text style={sStyle.success}>{message}</Text>:null}</View><Text style={sStyle.section}>Customers</Text>{data.map(c=><View style={sStyle.row} key={c._id}><View><Text style={sStyle.rowTitle}>{c.customerId} — {c.name}</Text><Text style={sStyle.muted}>{c.mobile}{c.city?" · "+c.city:""}</Text></View></View>)}</ScrollView>}
function Loans(){const[data,setData]=useState<Loan[]>([]);useEffect(()=>{token().then(t=>api.get("/loans",{headers:{Authorization:"Bearer "+t}}).then(r=>setData(r.data.data)))},[]);return <ScrollView contentContainerStyle={s.container}><Text style={sStyle.section}>Loan Applications</Text>{data.map(l=><View style={sStyle.row} key={l._id}><View><Text style={sStyle.rowTitle}>{l.loanId} — {l.customerId?.name}</Text><Text style={sStyle.muted}>{l.loanType} · ₹{l.requiredAmount.toLocaleString("en-IN")}</Text></View><Text style={sStyle.status}>{l.status}</Text></View>)}{!data.length&&<Text style={sStyle.muted}>No loan applications yet.</Text>}</ScrollView>}
function Profit(){
 const[data,setData]=useState<any>(null);
 useEffect(()=>{token().then(t=>api.get("/cars/profits",{headers:{Authorization:"Bearer "+t}}).then(r=>setData(r.data.data)))},[]);
 const s=data?.summary;
 return <ScrollView contentContainerStyle={sStyle.container}><Text style={sStyle.section}>Car Profit</Text><View style={sStyle.profitBox}><Text style={sStyle.label}>NET PROFIT</Text><Text style={sStyle.profit}>₹{(s?.profit??0).toLocaleString("en-IN")}</Text></View>{(data?.sales??[]).map((x:any)=><View style={sStyle.row} key={x._id}><View><Text style={sStyle.rowTitle}>{x.saleId} — {x.carId?.vehicleId}</Text><Text style={sStyle.muted}>{x.carId?.make} {x.carId?.model}</Text></View><Text style={sStyle.status}>₹{x.profit.toLocaleString("en-IN")}</Text></View>)}</ScrollView>
}
function Cars(){const[data,setData]=useState<Car[]>([]);useEffect(()=>{token().then(t=>api.get("/cars",{headers:{Authorization:"Bearer "+t}}).then(r=>setData(r.data.data)))},[]);return <ScrollView contentContainerStyle={s.container}><Text style={sStyle.section}>Car Inventory</Text>{data.map(c=><View style={sStyle.row} key={c._id}><View><Text style={sStyle.rowTitle}>{c.vehicleId} — {c.registrationNumber}</Text><Text style={sStyle.muted}>{c.make} {c.model} · ₹{c.purchasePrice.toLocaleString("en-IN")}</Text></View><Text style={sStyle.status}>{c.status}</Text></View>)}{!data.length&&<Text style={sStyle.muted}>No vehicles in inventory.</Text>}</ScrollView>}
function Stat({title,value}:{title:string;value:number}){return <View style={sStyle.stat}><Text style={sStyle.label}>{title}</Text><Text style={sStyle.statValue}>{value}</Text></View>}
const sStyle=StyleSheet.create({safe:{flex:1,backgroundColor:"#f5f6f8"},login:{flex:1,justifyContent:"center",padding:22,backgroundColor:"#111b2d"},loginCard:{backgroundColor:"#fff",borderRadius:18,padding:24},brand:{fontSize:14,fontWeight:"800",letterSpacing:2,color:"#111b2d"},loginTitle:{fontSize:28,fontWeight:"800",marginTop:18,color:"#18202a"},muted:{color:"#64748b",marginTop:5},inputLabel:{fontSize:13,fontWeight:"700",marginTop:18,marginBottom:7},input:{borderWidth:1,borderColor:"#d6dbe3",borderRadius:9,padding:12,fontSize:15,backgroundColor:"#fff",marginBottom:10},button:{backgroundColor:"#243653",padding:14,borderRadius:9,marginTop:10,alignItems:"center"},buttonText:{color:"#fff",fontWeight:"800"},error:{backgroundColor:"#fff1f2",color:"#b42318",padding:10,borderRadius:8,marginTop:14},success:{color:"#027a48",marginTop:10},center:{flex:1,alignItems:"center",justifyContent:"center"},header:{padding:18,flexDirection:"row",justifyContent:"space-between",alignItems:"flex-start"},headerTitle:{fontSize:27,fontWeight:"800",marginTop:14,color:"#18202a"},signout:{color:"#243653",fontWeight:"700"},tabs:{flexDirection:"row",paddingHorizontal:12,paddingBottom:8,gap:7},tab:{paddingVertical:9,paddingHorizontal:12,borderRadius:20},tabActive:{paddingVertical:9,paddingHorizontal:12,borderRadius:20,backgroundColor:"#243653"},tabText:{color:"#64748b",fontSize:12,fontWeight:"700"},tabTextActive:{color:"#fff",fontSize:12,fontWeight:"700"},container:{padding:18,paddingBottom:40},grid:{flexDirection:"row",flexWrap:"wrap",gap:10},stat:{width:"48%",backgroundColor:"#fff",borderRadius:14,padding:17},label:{color:"#64748b",fontSize:12},statValue:{fontSize:27,fontWeight:"800",marginTop:8,color:"#18202a"},profitBox:{backgroundColor:"#111b2d",borderRadius:16,padding:22,marginTop:12},profit:{color:"#fff",fontSize:29,fontWeight:"800",marginTop:8},section:{fontSize:19,fontWeight:"800",marginTop:18,marginBottom:10},card:{backgroundColor:"#fff",borderRadius:14,padding:17},row:{backgroundColor:"#fff",padding:16,borderRadius:12,marginBottom:9,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},rowTitle:{fontSize:14,fontWeight:"700",color:"#18202a"},status:{fontSize:10,fontWeight:"800",color:"#344054",backgroundColor:"#eef2ff",paddingHorizontal:8,paddingVertical:5,borderRadius:12}});