import React,{useEffect,useState} from 'react';
import {Alert,ActivityIndicator,Modal,Pressable,ScrollView,Text,TextInput,View} from 'react-native';
import {api} from '../api/client';
import {colors} from '../theme/colors';

const emptyExpense={carId:'',category:'Repair',description:'',amount:'',date:''};
export default function AdminToolsScreen({route,navigation}){
 const section=route?.params?.section||'Users';
 return <View style={s.page}>
 <View style={s.topBar}><Pressable onPress={()=>navigation.goBack()} style={s.back}><Ionicons name="arrow-back" size={22} color={colors.ink}/></Pressable><View style={{flex:1,marginLeft:10}}><Text style={s.topTitle}>{section}</Text><Text style={s.topSubtitle}>Admin management</Text></View></View>
 <View style={{flex:1}}>{section==='Users'?<Users/>:section==='Expenses'?<Expenses/>:<Reports section={section}/>}</View>
 </View>;
}
function Users(){
 const[items,setItems]=useState([]),[busy,setBusy]=useState(true),[modal,setModal]=useState(false),[editing,setEditing]=useState(null),[form,setForm]=useState({name:'',email:'',password:'',role:'STAFF',isActive:true});
 async function load(){setBusy(true);try{const r=await api.get('/auth/users');setItems(r.data?.data||[])}catch(e){Alert.alert('Users',e?.response?.data?.message||'Unable to load users.')}finally{setBusy(false)}}useEffect(()=>{load()},[]);
 function open(u){setEditing(u||null);setForm({name:u?.name||'',email:u?.email||'',password:'',role:u?.role||'STAFF',isActive:u?.isActive!==false});setModal(true)}
 async function save(){if(!form.name||!form.email||(!editing&&!form.password))return Alert.alert('User','Name, email and password are required for a new user.');try{const payload={...form};if(!payload.password)delete payload.password;if(editing)await api.patch('/auth/users/'+editing.id,payload);else await api.post('/auth/users',payload);setModal(false);load()}catch(e){Alert.alert('User',e?.response?.data?.message||'Unable to save user.')}}
 function remove(u){Alert.alert('Delete user','Delete '+u.name+'?',[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:async()=>{try{await api.delete('/auth/users/'+u.id);load()}catch(e){Alert.alert('Delete',e?.response?.data?.message||'Unable to delete user.')}}}])}
 return <View style={s.page}><Header title="User Management" add={()=>open(null)}/>{busy?<ActivityIndicator style={{marginTop:40}} color={colors.gold}/>:<ScrollView contentContainerStyle={s.list}>{items.map(u=><View style={s.card} key={u.id}><View style={{flex:1}}><Text style={s.titleSmall}>{u.name}</Text><Text style={s.muted}>{u.email}</Text><Text style={s.muted}>{u.role} · {u.isActive?'ACTIVE':'INACTIVE'}</Text></View><View style={s.actions}><Pressable onPress={()=>open(u)} style={s.secondary}><Text style={s.secondaryText}>Edit</Text></Pressable><Pressable onPress={()=>remove(u)} style={s.delete}><Text style={s.deleteText}>Delete</Text></Pressable></View></View>)}</ScrollView>}<UserModal visible={modal} form={form} setForm={setForm} editing={editing} close={()=>setModal(false)} save={save}/></View>
}
function UserModal({visible,form,setForm,editing,close,save}){return <Modal visible={visible} animationType="slide" transparent onRequestClose={close}><View style={s.overlay}><View style={s.modal}><View style={s.modalHead}><Text style={s.modalTitle}>{editing?'Edit User':'Create User'}</Text><Pressable onPress={close}><Text style={s.close}>×</Text></Pressable></View><ScrollView>{[['name','Name'],['email','Email'],['password',editing?'New Password':'Password']].map(([k,l])=><Field key={k} label={l} value={form[k]} onChangeText={v=>setForm(p=>({...p,[k]:v}))}/>)}<Field label="Role (ADMIN / STAFF)" value={form.role} onChangeText={v=>setForm(p=>({...p,role:v.toUpperCase()}))}/><Pressable onPress={()=>setForm(p=>({...p,isActive:!p.isActive}))} style={s.toggle}><Text style={s.secondaryText}>Account: {form.isActive?'ACTIVE':'INACTIVE'}</Text></Pressable><Pressable onPress={save} style={s.primary}><Text style={s.primaryText}>{editing?'Update User':'Create User'}</Text></Pressable></ScrollView></View></View></Modal>}
function Expenses(){
 const[items,setItems]=useState([]),[cars,setCars]=useState([]),[busy,setBusy]=useState(true),[modal,setModal]=useState(false),[editing,setEditing]=useState(null),[form,setForm]=useState(emptyExpense);
 async function load(){setBusy(true);try{const[r,c]=await Promise.all([api.get('/cars/expenses'),api.get('/cars')]);setItems(r.data?.data||[]);setCars(c.data?.data||[])}catch(e){Alert.alert('Expenses',e?.response?.data?.message||'Unable to load expenses.')}finally{setBusy(false)}}useEffect(()=>{load()},[]);
 function open(x){setEditing(x||null);setForm(x?{carId:x.carId?._id||'',category:x.category||'',description:x.description||'',amount:String(x.amount||''),date:x.date?String(x.date).slice(0,10):''}:{...emptyExpense});setModal(true)}
 async function save(){if(!form.carId||!form.amount)return Alert.alert('Expense','Vehicle and amount are required.');try{if(editing)await api.patch('/cars/expenses/'+editing._id,{category:form.category,description:form.description,amount:Number(form.amount),date:form.date||undefined});else await api.post('/cars/'+form.carId+'/expenses',{category:form.category,description:form.description,amount:Number(form.amount),date:form.date||undefined});setModal(false);load()}catch(e){Alert.alert('Expense',e?.response?.data?.message||'Unable to save expense.')}}
 function remove(x){Alert.alert('Delete expense','Delete this expense?',[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:async()=>{try{await api.delete('/cars/'+(x.carId?._id||x.carId)+'/expenses/'+x._id);load()}catch(e){Alert.alert('Delete',e?.response?.data?.message||'Unable to delete expense.')}}}])}
 return <View style={s.page}><Header title="Vehicle Expenses" add={()=>open(null)}/>{busy?<ActivityIndicator style={{marginTop:40}} color={colors.gold}/>:<ScrollView contentContainerStyle={s.list}>{items.map(x=><View style={s.card} key={x._id}><View style={{flex:1}}><Text style={s.titleSmall}>{x.carId?.vehicleId||'Vehicle'}</Text><Text style={s.muted}>{x.category} · {x.description||'—'}</Text><Text style={s.money}>₹{Number(x.amount||0).toLocaleString('en-IN')}</Text></View><View style={s.actions}><Pressable onPress={()=>open(x)} style={s.secondary}><Text style={s.secondaryText}>Edit</Text></Pressable><Pressable onPress={()=>remove(x)} style={s.delete}><Text style={s.deleteText}>Delete</Text></Pressable></View></View>)}</ScrollView>}<Modal visible={modal} animationType="slide" transparent onRequestClose={()=>setModal(false)}><View style={s.overlay}><View style={s.modal}><View style={s.modalHead}><Text style={s.modalTitle}>{editing?'Edit Expense':'Add Expense'}</Text><Pressable onPress={()=>setModal(false)}><Text style={s.close}>×</Text></Pressable></View><ScrollView>{!editing&&<><Text style={s.label}>Vehicle</Text><View style={{gap:8,marginBottom:12}}>{cars.map(c=><Pressable key={c._id} onPress={()=>setForm(p=>({...p,carId:c._id}))} style={[s.option,form.carId===c._id&&s.optionActive]}><Text style={s.secondaryText}>{c.vehicleId} — {c.registrationNumber}</Text></Pressable>)}</View></>}<Field label="Category" value={form.category} onChangeText={v=>setForm(p=>({...p,category:v}))}/><Field label="Description" value={form.description} onChangeText={v=>setForm(p=>({...p,description:v}))}/><Field label="Amount" value={form.amount} onChangeText={v=>setForm(p=>({...p,amount:v}))} keyboardType="numeric"/><Field label="Date (YYYY-MM-DD)" value={form.date} onChangeText={v=>setForm(p=>({...p,date:v}))}/><Pressable onPress={save} style={s.primary}><Text style={s.primaryText}>{editing?'Update Expense':'Add Expense'}</Text></Pressable></ScrollView></View></View></Modal></View>
}
function Reports({section}){const[data,setData]=useState(null),[busy,setBusy]=useState(true);useEffect(()=>{(async()=>{try{const endpoint=section==='Car Profit'?'/cars/profits':section==='Loan Revenue'?'/reports/loan-revenue':'/reports/operational';const r=await api.get(endpoint);setData(r.data?.data)}catch(e){Alert.alert('Reports',e?.response?.data?.message||'Unable to load report.')}finally{setBusy(false)}})()},[section]);return <View style={s.page}><View style={s.head}><Text style={s.title}>{section}</Text><Text style={s.subtitle}>Admin report from the same backend used by web.</Text></View>{busy?<ActivityIndicator style={{marginTop:40}} color={colors.gold}/>:<ScrollView contentContainerStyle={s.list}><View style={s.reportCard}><Text style={s.titleSmall}>Report data</Text><Text style={s.muted}>{JSON.stringify(data,null,2)}</Text></View></ScrollView>}</View>}
function Header({title,add}){return <View style={s.head}><View><Text style={s.title}>{title}</Text><Text style={s.subtitle}>Admin-only management access.</Text></View><Pressable onPress={add} style={s.add}><Text style={s.addText}>+</Text></Pressable></View>}
function Field({label,value,onChangeText,keyboardType}){return <View style={{marginBottom:11}}><Text style={s.label}>{label}</Text><TextInput value={String(value??'')} onChangeText={onChangeText} keyboardType={keyboardType} placeholder={'Enter '+label.toLowerCase()} placeholderTextColor="#9AA4AD" style={s.input}/></View>}
const s={page:{flex:1,backgroundColor:colors.ivory},topBar:{height:76,paddingHorizontal:18,flexDirection:'row',alignItems:'center',backgroundColor:colors.ivory},back:{width:44,height:44,borderRadius:14,backgroundColor:colors.white,alignItems:'center',justifyContent:'center'},topTitle:{fontSize:20,fontWeight:'900',color:colors.ink},topSubtitle:{fontSize:11,color:colors.muted,marginTop:2},oldPage:{flex:1,backgroundColor:colors.ivory,paddingTop:58},head:{paddingHorizontal:18,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},title:{fontSize:28,fontWeight:'900',color:colors.ink},subtitle:{color:colors.muted,fontSize:13,marginTop:4},add:{width:46,height:46,borderRadius:15,backgroundColor:colors.midnight,alignItems:'center',justifyContent:'center'},addText:{fontSize:27,color:colors.goldLight,lineHeight:30},list:{padding:18,paddingBottom:30},card:{backgroundColor:colors.white,borderRadius:20,padding:16,marginBottom:10,borderWidth:1,borderColor:'#E5E7E4'},titleSmall:{fontSize:16,fontWeight:'900',color:colors.ink},muted:{color:colors.muted,fontSize:12,marginTop:4},money:{fontSize:16,fontWeight:'900',color:colors.teal,marginTop:7},actions:{flexDirection:'row',gap:8,marginTop:12},secondary:{height:42,paddingHorizontal:18,borderRadius:12,borderWidth:1,borderColor:'#DDE1DE',alignItems:'center',justifyContent:'center'},secondaryText:{color:colors.midnight,fontWeight:'900'},delete:{height:42,paddingHorizontal:18,borderRadius:12,backgroundColor:'#FFF2F2',alignItems:'center',justifyContent:'center'},deleteText:{color:colors.danger,fontWeight:'900'},overlay:{flex:1,backgroundColor:'rgba(0,0,0,.45)',justifyContent:'flex-end'},modal:{backgroundColor:colors.ivory,maxHeight:'92%',borderTopLeftRadius:28,borderTopRightRadius:28,padding:18},modalHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:12},modalTitle:{fontSize:21,fontWeight:'900',color:colors.ink},close:{fontSize:30,color:colors.ink},label:{fontSize:11,fontWeight:'900',color:colors.ink,marginBottom:6},input:{height:49,borderRadius:14,borderWidth:1,borderColor:'#DDE1DE',backgroundColor:colors.white,paddingHorizontal:13,color:colors.ink},toggle:{height:48,borderRadius:14,backgroundColor:colors.white,borderWidth:1,borderColor:'#DDE1DE',alignItems:'center',justifyContent:'center',marginBottom:12},primary:{height:54,borderRadius:16,backgroundColor:colors.gold,alignItems:'center',justifyContent:'center',marginTop:12},primaryText:{color:colors.midnight,fontWeight:'900'},option:{padding:13,borderRadius:13,backgroundColor:colors.white,borderWidth:1,borderColor:'#E5E7E4'},optionActive:{borderColor:colors.gold,backgroundColor:'#FFF9E8'},reportCard:{backgroundColor:colors.white,borderRadius:20,padding:16}};
