import React,{useEffect,useState} from 'react';
import {Alert,ActivityIndicator,Modal,Pressable,ScrollView,Text,TextInput,View} from 'react-native';
import {api,uploadDocument} from '../api/client';
import {colors} from '../theme/colors';
import DocumentPickerButton from '../components/DocumentPickerButton';

export default function CarSaleScreen(){
 const[cars,setCars]=useState([]),[customers,setCustomers]=useState([]),[busy,setBusy]=useState(true),[carId,setCarId]=useState(''),[buyerId,setBuyerId]=useState(''),[price,setPrice]=useState(''),[expenses,setExpenses]=useState('0'),[files,setFiles]=useState({}),[customName,setCustomName]=useState(''),[customDocs,setCustomDocs]=useState([]),[saving,setSaving]=useState(false);
 async function load(){setBusy(true);try{const[r,c]=await Promise.all([api.get('/cars',{params:{status:'AVAILABLE'}}),api.get('/customers')]);setCars(r.data?.data||[]);setCustomers(c.data?.data||[])}catch(e){Alert.alert('Car Sale',e?.response?.data?.message||'Unable to load sale data.')}finally{setBusy(false)}}useEffect(()=>{load()},[]);
 async function sell(){if(!carId||!buyerId||!price)return Alert.alert('Car Sale','Vehicle, buyer and selling price are required.');setSaving(true);try{const r=await api.post('/cars/'+carId+'/sell',{buyerId,sellingPrice:Number(price),sellingExpenses:Number(expenses||0),documents:{idProof:Boolean(files.idProof),agreement:Boolean(files.agreement),customDocuments:customDocs}});for(const key of ['idProof','agreement'])if(files[key])await uploadDocument('/cars/'+carId+'/sale/documents/'+key,files[key]);for(const name of customDocs)if(files['custom:'+name])await uploadDocument('/cars/'+carId+'/sale/documents/custom',files['custom:'+name],{documentName:name});Alert.alert('Sale Completed','Vehicle sold successfully. Net profit: ₹'+Number(r.data?.data?.profit||0).toLocaleString('en-IN'));setCarId('');setBuyerId('');setPrice('');setExpenses('0');setFiles({});setCustomDocs([]);load()}catch(e){Alert.alert('Car Sale',e?.response?.data?.message||'Unable to complete sale.')}finally{setSaving(false)}}
 return <View style={s.page}><View style={s.head}><View><Text style={s.title}>Car Sold</Text><Text style={s.subtitle}>Sell inventory vehicles and calculate profit.</Text></View></View>{busy?<ActivityIndicator style={{marginTop:40}} color={colors.gold}/>:<ScrollView contentContainerStyle={s.list}><Text style={s.label}>Vehicle</Text>{cars.map(c=><Pressable key={c._id} onPress={()=>setCarId(c._id)} style={[s.option,carId===c._id&&s.active]}><Text style={s.cardTitle}>{c.vehicleId} — {c.make} {c.model}</Text><Text style={s.muted}>{c.registrationNumber} · ₹{Number(c.purchasePrice||0).toLocaleString('en-IN')}</Text></Pressable>)}<Text style={s.label}>Buyer</Text>{customers.map(c=><Pressable key={c._id} onPress={()=>setBuyerId(c._id)} style={[s.option,buyerId===c._id&&s.active]}><Text style={s.cardTitle}>{c.customerId} — {c.name}</Text><Text style={s.muted}>{c.mobile}</Text></Pressable>)}<Field label="Selling Price" value={price} onChangeText={setPrice}/><Field label="Selling Expenses" value={expenses} onChangeText={setExpenses}/><Text style={s.section}>Buyer Documents</Text>{[['idProof','ID Proof'],['agreement','Agreement']].map(([key,title])=><View key={key} style={s.doc}><Text style={s.cardTitle}>{title}</Text><DocumentPickerButton file={files[key]} onPick={f=>setFiles(p=>({...p,[key]:f}))}/></View>)}<View style={s.customRow}><TextInput value={customName} onChangeText={setCustomName} placeholder="Custom document name" placeholderTextColor="#9AA4AD" style={[s.input,{flex:1}]}/><Pressable onPress={()=>{const n=customName.trim();if(n&&!customDocs.includes(n)){setCustomDocs(p=>[...p,n]);setCustomName('')}}} style={s.add}><Text style={s.addText}>Add</Text></Pressable></View>{customDocs.map(n=><View key={n} style={s.doc}><Text style={s.cardTitle}>{n}</Text><DocumentPickerButton file={files['custom:'+n]} onPick={f=>setFiles(p=>({...p,['custom:'+n]:f}))}/></View>)}<Pressable disabled={saving} onPress={sell} style={s.primary}><Text style={s.primaryText}>{saving?'Completing...':'Complete Sale'}</Text></Pressable></ScrollView>}</View>
}
function Field({label,value,onChangeText}){return <View style={{marginBottom:12}}><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={onChangeText} keyboardType="numeric" placeholder={'Enter '+label.toLowerCase()} placeholderTextColor="#9AA4AD" style={s.input}/></View>}
const s={page:{flex:1,backgroundColor:colors.ivory,paddingTop:58},head:{paddingHorizontal:18},title:{fontSize:28,fontWeight:'900',color:colors.ink},subtitle:{color:colors.muted,fontSize:13,marginTop:4},list:{padding:18,paddingBottom:40},label:{fontSize:11,fontWeight:'900',color:colors.ink,marginTop:8,marginBottom:7},option:{backgroundColor:colors.white,borderWidth:1,borderColor:'#E5E7E4',borderRadius:15,padding:13,marginBottom:8},active:{borderColor:colors.gold,backgroundColor:'#FFF9E8'},cardTitle:{fontSize:14,fontWeight:'900',color:colors.ink},muted:{fontSize:11,color:colors.muted,marginTop:4},input:{height:49,borderRadius:14,borderWidth:1,borderColor:'#DDE1DE',backgroundColor:colors.white,paddingHorizontal:13,color:colors.ink},section:{fontSize:18,fontWeight:'900',color:colors.ink,marginTop:10},doc:{backgroundColor:colors.white,borderRadius:16,padding:12,marginTop:10,borderWidth:1,borderColor:'#E5E7E4'},customRow:{flexDirection:'row',gap:8,marginTop:12},add:{width:65,height:49,borderRadius:14,backgroundColor:colors.midnight,alignItems:'center',justifyContent:'center'},addText:{color:colors.goldLight,fontWeight:'900'},primary:{height:55,borderRadius:16,backgroundColor:colors.gold,alignItems:'center',justifyContent:'center',marginTop:20},primaryText:{color:colors.midnight,fontWeight:'900',fontSize:15}};
