import {AppText,AppTextInput} from '../components/AppText';
import React,{useEffect,useState} from 'react';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import {ActivityIndicator, Alert, ScrollView, View, Pressable} from 'react-native';
import {Ionicons} from '@expo/vector-icons';
import {api} from '../api/client';
import {colors} from '../theme/colors';

const money=v=>'₹'+Number(v||0).toLocaleString('en-IN');
function Layout({title,children,navigation}){ const {top}=useSafeAreaInsets();return <View style={[s.page,{paddingTop:Math.max(22,top+22)}]}><View style={s.header}><Pressable onPress={()=>navigation.goBack()} style={s.back}><Ionicons name="arrow-back" size={22} color={colors.ink}/></Pressable><View><AppText style={s.title}>{title}</AppText><AppText style={s.sub}>SM Associate report</AppText></View></View><ScrollView contentContainerStyle={s.list}>{children}</ScrollView></View>}
function Loading(){return <ActivityIndicator style={{marginTop:50}} color={colors.gold}/>}
function Stat({label,value,icon}){return <View style={s.stat}><View style={s.statIcon}><Ionicons name={icon} size={18} color={colors.teal}/></View><AppText style={s.label}>{label}</AppText><AppText style={s.value}>{value}</AppText></View>}
export function CarProfitScreen({navigation}){const[d,setD]=useState(null);useEffect(()=>{api.get('/cars/profits').then(r=>setD(r.data?.data||{})).catch(e=>Alert.alert('Car Profit',e?.response?.data?.message||'Unable to load report.'))},[]);if(!d)return <Layout title="Car Profit" navigation={navigation}><Loading/></Layout>;const x=d.summary||{};return <Layout title="Car Profit" navigation={navigation}><View style={s.grid}><Stat label="Total Sales" value={money(x.sales)} icon="cart-outline"/><Stat label="Investment" value={money(x.investment)} icon="wallet-outline"/><Stat label="Selling Expenses" value={money(x.sellingExpenses)} icon="receipt-outline"/><Stat label="Net Profit" value={money(x.profit)} icon="trending-up-outline"/></View><AppText style={s.section}>Vehicle-wise Profit</AppText>{(d.sales||[]).map((x,i)=><View style={s.card} key={x._id||i}><View style={s.cardIcon}><Ionicons name="car-sport-outline" size={21} color={colors.teal}/></View><View style={{flex:1}}><AppText style={s.name}>{x.carId?.vehicleId||'Vehicle'}</AppText><AppText style={s.muted}>{[x.carId?.make,x.carId?.model,x.carId?.registrationNumber].filter(Boolean).join(' · ')||'Vehicle details'}</AppText><AppText style={s.muted}>Buyer: {x.buyerId?.name||'—'}</AppText></View><AppText style={s.profit}>{money(x.profit)}</AppText></View>)}</Layout>}
export function LoanRevenueScreen({navigation}){const[d,setD]=useState(null);useEffect(()=>{api.get('/reports/loan-revenue').then(r=>setD(r.data?.data||{})).catch(e=>Alert.alert('Loan Revenue',e?.response?.data?.message||'Unable to load report.'))},[]);if(!d)return <Layout title="Loan Revenue" navigation={navigation}><Loading/></Layout>;const x=d.summary||{};return <Layout title="Loan Revenue" navigation={navigation}><View style={s.grid}><Stat label="Total Commission" value={money(x.totalCommission)} icon="cash-outline"/><Stat label="Disbursed Revenue" value={money(x.disbursedCommission)} icon="checkmark-circle-outline"/><Stat label="Approved+" value={x.approvedOrBetter||0} icon="thumbs-up-outline"/><Stat label="Loan Records" value={(d.loans||[]).length} icon="document-text-outline"/></View><AppText style={s.section}>Revenue by Loan Type</AppText>{Object.entries(d.byType||{}).map(([k,v])=><View style={s.row} key={k}><View style={s.rowIcon}><Ionicons name="cash-outline" size={18} color={colors.teal}/></View><AppText style={s.name}>{k}</AppText><AppText style={s.profit}>{money(v)}</AppText></View>)}<AppText style={s.section}>Revenue by Finance Company</AppText>{Object.entries(d.byFinance||{}).map(([k,v])=><View style={s.row} key={k}><View style={s.rowIcon}><Ionicons name="business-outline" size={18} color={colors.teal}/></View><AppText style={s.name}>{k}</AppText><AppText style={s.profit}>{money(v)}</AppText></View>)}</Layout>}
export function OperationalReportsScreen({navigation}){const[d,setD]=useState(null);useEffect(()=>{api.get('/reports/operational').then(r=>setD(r.data?.data||{})).catch(e=>Alert.alert('Operational Reports',e?.response?.data?.message||'Unable to load report.'))},[]);if(!d)return <Layout title="Operational Reports" navigation={navigation}><Loading/></Layout>;const l=d.loanSummary||{},sales=d.sales||{},ex=d.carExpenses||{};return <Layout title="Operational Reports" navigation={navigation}><View style={s.grid}><Stat label="Customers" value={Array.isArray(d.customers)?d.customers.length:d.customers||0} icon="people-outline"/><Stat label="Total Loans" value={l.count||0} icon="cash-outline"/><Stat label="Open Follow-ups" value={(d.openFollowUps||[]).length} icon="call-outline"/><Stat label="Inventory" value={(d.inventory||[]).length} icon="car-sport-outline"/><Stat label="Cars Sold" value={sales.count||0} icon="car-sport-outline"/><Stat label="Sales Profit" value={money(sales.profit)} icon="trending-up-outline"/><Stat label="Car Expenses" value={money(ex.total)} icon="receipt-outline"/><Stat label="Expense Records" value={ex.count||0} icon="document-text-outline"/></View><AppText style={s.section}>Loans by Status</AppText>{Object.entries(l.byStatus||{}).map(([k,v])=><View style={s.row} key={k}><AppText style={s.name}>{k}</AppText><AppText style={s.badge}>{v}</AppText></View>)}<AppText style={s.section}>Loans by Type</AppText>{Object.entries(l.byType||{}).map(([k,v])=><View style={s.row} key={k}><AppText style={s.name}>{k}</AppText><AppText style={s.badge}>{v}</AppText></View>)}<AppText style={s.section}>Current Inventory</AppText>{(d.inventory||[]).map((x,i)=><View style={s.card} key={x._id||i}><View style={s.cardIcon}><Ionicons name="car-sport-outline" size={21} color={colors.teal}/></View><View style={{flex:1}}><AppText style={s.name}>{x.vehicleId||'Vehicle'}</AppText><AppText style={s.muted}>{[x.make,x.model,x.registrationNumber].filter(Boolean).join(' · ')}</AppText></View><AppText style={s.profit}>{money(x.purchasePrice)}</AppText></View>)}</Layout>}
const s={page:{flex:1,backgroundColor:'#F4F6F3',paddingTop:0},header:{height:72,paddingHorizontal:18,flexDirection:'row',alignItems:'center',gap:12},back:{width:44,height:44,borderRadius:14,backgroundColor:colors.white,alignItems:'center',justifyContent:'center'},title:{fontSize:23,color:colors.ink},sub:{fontSize:11,color:colors.muted,marginTop:2},list:{padding:18,paddingBottom:35},grid:{flexDirection:'row',flexWrap:'wrap',gap:10},stat:{width:'48%',minHeight:104,borderRadius:22,backgroundColor:colors.white,padding:14,justifyContent:'center',borderWidth:1,borderColor:'rgba(39,168,154,0.13)'},statIcon:{width:34,height:34,borderRadius:11,backgroundColor:'#E2F1EE',alignItems:'center',justifyContent:'center',marginBottom:8},label:{fontSize:11,color:colors.muted},value:{fontSize:21,color:colors.teal,marginTop:5},section:{fontSize:18,color:colors.ink,marginTop:20,marginBottom:9},card:{backgroundColor:'#FFFFFF',borderRadius:22,padding:14,marginBottom:9,flexDirection:'row',alignItems:'center',borderWidth:1,borderColor:'rgba(39,168,154,0.13)'},cardIcon:{width:42,height:42,borderRadius:13,backgroundColor:'#E2F1EE',alignItems:'center',justifyContent:'center',marginRight:11},row:{backgroundColor:colors.white,borderRadius:15,padding:14,marginBottom:8,flexDirection:'row',alignItems:'center',borderWidth:1,borderColor:'rgba(39,168,154,0.13)'},rowIcon:{width:34,height:34,borderRadius:10,backgroundColor:'#E2F1EE',alignItems:'center',justifyContent:'center',marginRight:10},name:{fontSize:15,color:colors.ink},muted:{fontSize:12,color:colors.muted,marginTop:4},profit:{fontSize:15,color:colors.teal},badge:{color:colors.midnight,backgroundColor:colors.goldLight,paddingHorizontal:10,paddingVertical:5,borderRadius:10}};