import React,{useEffect,useState} from 'react';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import {ActivityIndicator,Alert,ScrollView,Text,View,Pressable} from 'react-native';
import {Ionicons} from '@expo/vector-icons';
import {api} from '../api/client';
import {colors} from '../theme/colors';

const money=v=>'₹'+Number(v||0).toLocaleString('en-IN');
function Layout({title,children,navigation}){ const {top}=useSafeAreaInsets();return <View style={[s.page,{paddingTop:Math.max(14,top+14)}]}><View style={s.header}><Pressable onPress={()=>navigation.goBack()} style={s.back}><Ionicons name="arrow-back" size={22} color={colors.ink}/></Pressable><View><Text style={s.title}>{title}</Text><Text style={s.sub}>SM Associate report</Text></View></View><ScrollView contentContainerStyle={s.list}>{children}</ScrollView></View>}
function Loading(){return <ActivityIndicator style={{marginTop:50}} color={colors.gold}/>}
function Stat({label,value}){return <View style={s.stat}><Text style={s.label}>{label}</Text><Text style={s.value}>{value}</Text></View>}
export function CarProfitScreen({navigation}){const[d,setD]=useState(null);useEffect(()=>{api.get('/cars/profits').then(r=>setD(r.data?.data||{})).catch(e=>Alert.alert('Car Profit',e?.response?.data?.message||'Unable to load report.'))},[]);if(!d)return <Layout title="Car Profit" navigation={navigation}><Loading/></Layout>;const x=d.summary||{};return <Layout title="Car Profit" navigation={navigation}><View style={s.grid}><Stat label="Total Sales" value={money(x.sales)}/><Stat label="Investment" value={money(x.investment)}/><Stat label="Selling Expenses" value={money(x.sellingExpenses)}/><Stat label="Net Profit" value={money(x.profit)}/></View><Text style={s.section}>Vehicle-wise Profit</Text>{(d.sales||[]).map((x,i)=><View style={s.card} key={x._id||i}><View style={{flex:1}}><Text style={s.name}>{x.carId?.vehicleId||'Vehicle'}</Text><Text style={s.muted}>{[x.carId?.make,x.carId?.model,x.carId?.registrationNumber].filter(Boolean).join(' · ')||'Vehicle details'}</Text><Text style={s.muted}>Buyer: {x.buyerId?.name||'—'}</Text></View><Text style={s.profit}>{money(x.profit)}</Text></View>)}</Layout>}
export function LoanRevenueScreen({navigation}){const[d,setD]=useState(null);useEffect(()=>{api.get('/reports/loan-revenue').then(r=>setD(r.data?.data||{})).catch(e=>Alert.alert('Loan Revenue',e?.response?.data?.message||'Unable to load report.'))},[]);if(!d)return <Layout title="Loan Revenue" navigation={navigation}><Loading/></Layout>;const x=d.summary||{};return <Layout title="Loan Revenue" navigation={navigation}><View style={s.grid}><Stat label="Total Commission" value={money(x.totalCommission)}/><Stat label="Disbursed Revenue" value={money(x.disbursedCommission)}/><Stat label="Approved+" value={x.approvedOrBetter||0}/><Stat label="Loan Records" value={(d.loans||[]).length}/></View><Text style={s.section}>Revenue by Loan Type</Text>{Object.entries(d.byType||{}).map(([k,v])=><View style={s.row} key={k}><Text style={s.name}>{k}</Text><Text style={s.profit}>{money(v)}</Text></View>)}<Text style={s.section}>Revenue by Finance Company</Text>{Object.entries(d.byFinance||{}).map(([k,v])=><View style={s.row} key={k}><Text style={s.name}>{k}</Text><Text style={s.profit}>{money(v)}</Text></View>)}</Layout>}
export function OperationalReportsScreen({navigation}){const[d,setD]=useState(null);useEffect(()=>{api.get('/reports/operational').then(r=>setD(r.data?.data||{})).catch(e=>Alert.alert('Operational Reports',e?.response?.data?.message||'Unable to load report.'))},[]);if(!d)return <Layout title="Operational Reports" navigation={navigation}><Loading/></Layout>;const l=d.loanSummary||{},sales=d.sales||{},ex=d.carExpenses||{};return <Layout title="Operational Reports" navigation={navigation}><View style={s.grid}><Stat label="Customers" value={Array.isArray(d.customers)?d.customers.length:d.customers||0}/><Stat label="Total Loans" value={l.count||0}/><Stat label="Open Follow-ups" value={(d.openFollowUps||[]).length}/><Stat label="Inventory" value={(d.inventory||[]).length}/><Stat label="Cars Sold" value={sales.count||0}/><Stat label="Sales Profit" value={money(sales.profit)}/><Stat label="Car Expenses" value={money(ex.total)}/><Stat label="Expense Records" value={ex.count||0}/></View><Text style={s.section}>Loans by Status</Text>{Object.entries(l.byStatus||{}).map(([k,v])=><View style={s.row} key={k}><Text style={s.name}>{k}</Text><Text style={s.badge}>{v}</Text></View>)}<Text style={s.section}>Loans by Type</Text>{Object.entries(l.byType||{}).map(([k,v])=><View style={s.row} key={k}><Text style={s.name}>{k}</Text><Text style={s.badge}>{v}</Text></View>)}<Text style={s.section}>Current Inventory</Text>{(d.inventory||[]).map((x,i)=><View style={s.card} key={x._id||i}><View style={{flex:1}}><Text style={s.name}>{x.vehicleId||'Vehicle'}</Text><Text style={s.muted}>{[x.make,x.model,x.registrationNumber].filter(Boolean).join(' · ')}</Text></View><Text style={s.profit}>{money(x.purchasePrice)}</Text></View>)}</Layout>}
const s={page:{flex:1,backgroundColor:'#F4F6F3',paddingTop:0},header:{height:72,paddingHorizontal:18,flexDirection:'row',alignItems:'center',gap:12},back:{width:44,height:44,borderRadius:14,backgroundColor:colors.white,alignItems:'center',justifyContent:'center'},title:{fontSize:23,fontWeight:'900',color:colors.ink},sub:{fontSize:11,color:colors.muted,marginTop:2},list:{padding:18,paddingBottom:35},grid:{flexDirection:'row',flexWrap:'wrap',gap:10},stat:{width:'48%',minHeight:104,borderRadius:22,backgroundColor:colors.white,padding:16,justifyContent:'center',borderWidth:1,borderColor:'rgba(39,168,154,0.13)'},label:{fontSize:11,fontWeight:'800',color:colors.muted},value:{fontSize:21,fontWeight:'900',color:colors.teal,marginTop:5},section:{fontSize:18,fontWeight:'900',color:colors.ink,marginTop:20,marginBottom:9},card:{backgroundColor:'#FFFFFF',borderRadius:22,padding:14,marginBottom:9,flexDirection:'row',alignItems:'center',borderWidth:1,borderColor:'rgba(39,168,154,0.13)'},row:{backgroundColor:colors.white,borderRadius:15,padding:14,marginBottom:8,flexDirection:'row',justifyContent:'space-between',alignItems:'center',borderWidth:1,borderColor:'rgba(39,168,154,0.13)'},name:{fontSize:15,fontWeight:'900',color:colors.ink},muted:{fontSize:12,color:colors.muted,marginTop:4},profit:{fontSize:15,fontWeight:'900',color:colors.teal},badge:{fontWeight:'900',color:colors.midnight,backgroundColor:colors.goldLight,paddingHorizontal:10,paddingVertical:5,borderRadius:10}};